#Inputs
set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN V16 [get_ports RESET]
    set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property PACKAGE_PIN V17 [get_ports ENABLE]
    set_property IOSTANDARD LVCMOS33 [get_ports ENABLE]

#Outputs
set_property PACKAGE_PIN W7 [get_ports {HEX_TO_CELL[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_TO_CELL[0]}]
set_property PACKAGE_PIN W6 [get_ports {HEX_TO_CELL[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_TO_CELL[1]}]
set_property PACKAGE_PIN U8 [get_ports {HEX_TO_CELL[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_TO_CELL[2]}]
set_property PACKAGE_PIN V8 [get_ports {HEX_TO_CELL[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_TO_CELL[3]}]
set_property PACKAGE_PIN U5 [get_ports {HEX_TO_CELL[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_TO_CELL[4]}]
set_property PACKAGE_PIN V5 [get_ports {HEX_TO_CELL[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_TO_CELL[5]}]
set_property PACKAGE_PIN U7 [get_ports {HEX_TO_CELL[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_TO_CELL[6]}]
set_property PACKAGE_PIN V7 [get_ports {HEX_TO_CELL[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_TO_CELL[7]}]
set_property PACKAGE_PIN U2 [get_ports {SEGMENT_SELECT[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_SELECT[0]}]
set_property PACKAGE_PIN U4 [get_ports {SEGMENT_SELECT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_SELECT[1]}]
set_property PACKAGE_PIN V4 [get_ports {SEGMENT_SELECT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_SELECT[2]}]
set_property PACKAGE_PIN W4 [get_ports {SEGMENT_SELECT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT_SELECT[3]}]