#Inputs
set_property PACKAGE_PIN V17 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN U18 [get_ports IN]
        set_property IOSTANDARD LVCMOS33 [get_ports IN]

#Outputs
set_property PACKAGE_PIN U16 [get_ports {OUT[0]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[0]}]
set_property PACKAGE_PIN E19 [get_ports {OUT[1]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[1]}]
set_property PACKAGE_PIN U19 [get_ports {OUT[2]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[2]}]
set_property PACKAGE_PIN V19 [get_ports {OUT[3]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[3]}]
set_property PACKAGE_PIN W18 [get_ports {OUT[4]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[4]}]
set_property PACKAGE_PIN U15 [get_ports {OUT[5]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[5]}]
set_property PACKAGE_PIN U14 [get_ports {OUT[6]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[6]}]
set_property PACKAGE_PIN V14 [get_ports {OUT[7]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[7]}]
set_property PACKAGE_PIN V13 [get_ports {OUT[8]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[8]}]
set_property PACKAGE_PIN V3 [get_ports {OUT[9]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[9]}]
set_property PACKAGE_PIN W3 [get_ports {OUT[10]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[10]}]
set_property PACKAGE_PIN U3 [get_ports {OUT[11]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[11]}]
set_property PACKAGE_PIN P3 [get_ports {OUT[12]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[12]}]
set_property PACKAGE_PIN N3 [get_ports {OUT[13]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[13]}]
set_property PACKAGE_PIN P1 [get_ports {OUT[14]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[14]}]
set_property PACKAGE_PIN L1 [get_ports {OUT[15]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {OUT[15]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK_IBUF]